// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG23rEb_l5eo-CRgpu-FHPUaVGqxcXKVI',
    appId: '1:812191093437:web:08648d42622bdd4e0c1dd4',
    messagingSenderId: '812191093437',
    projectId: 'veridian-app-19622',
    authDomain: 'veridian-app-19622.firebaseapp.com',
    storageBucket: 'veridian-app-19622.firebasestorage.app',
    measurementId: 'G-L7SESRV4TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOqJ1wmQNYiZcpYo8gLzC1NwoNLRU6rqs',
    appId: '1:812191093437:android:f3ea7ad059af21940c1dd4',
    messagingSenderId: '812191093437',
    projectId: 'veridian-app-19622',
    storageBucket: 'veridian-app-19622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2n3cKxZjkqJO0AEvzzV--i54IdRaeIk',
    appId: '1:812191093437:ios:89c7f8cdeafacf860c1dd4',
    messagingSenderId: '812191093437',
    projectId: 'veridian-app-19622',
    storageBucket: 'veridian-app-19622.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2n3cKxZjkqJO0AEvzzV--i54IdRaeIk',
    appId: '1:812191093437:ios:89c7f8cdeafacf860c1dd4',
    messagingSenderId: '812191093437',
    projectId: 'veridian-app-19622',
    storageBucket: 'veridian-app-19622.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG23rEb_l5eo-CRgpu-FHPUaVGqxcXKVI',
    appId: '1:812191093437:web:a3a7bc11f9b0d5c90c1dd4',
    messagingSenderId: '812191093437',
    projectId: 'veridian-app-19622',
    authDomain: 'veridian-app-19622.firebaseapp.com',
    storageBucket: 'veridian-app-19622.firebasestorage.app',
    measurementId: 'G-D7C07TXJLM',
  );
}
